// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SysLog.Repository.Data;

#nullable disable

namespace SysLog.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SysLog.Domine.Model.Acction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcctionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LogId")
                        .IsUnique();

                    b.ToTable("actions", (string)null);
                });

            modelBuilder.Entity("SysLog.Domine.Model.Interface", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogId")
                        .IsUnique();

                    b.ToTable("interfaces", (string)null);
                });

            modelBuilder.Entity("SysLog.Domine.Model.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpDestiny")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpOut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogId");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("SysLog.Domine.Model.LogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogId")
                        .IsUnique();

                    b.ToTable("logs_type", (string)null);
                });

            modelBuilder.Entity("SysLog.Domine.Model.Protocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogId")
                        .IsUnique();

                    b.ToTable("protocols", (string)null);
                });

            modelBuilder.Entity("SysLog.Domine.Model.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LogTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogTypeId")
                        .IsUnique();

                    b.ToTable("signatures", (string)null);
                });

            modelBuilder.Entity("SysLog.Domine.Model.Acction", b =>
                {
                    b.HasOne("SysLog.Domine.Model.Log", "Log")
                        .WithOne("Acction")
                        .HasForeignKey("SysLog.Domine.Model.Acction", "LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("SysLog.Domine.Model.Interface", b =>
                {
                    b.HasOne("SysLog.Domine.Model.Log", "Log")
                        .WithOne("Interface")
                        .HasForeignKey("SysLog.Domine.Model.Interface", "LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("SysLog.Domine.Model.LogType", b =>
                {
                    b.HasOne("SysLog.Domine.Model.Log", "Log")
                        .WithOne("LogType")
                        .HasForeignKey("SysLog.Domine.Model.LogType", "LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("SysLog.Domine.Model.Protocol", b =>
                {
                    b.HasOne("SysLog.Domine.Model.Log", "Log")
                        .WithOne("Protocol")
                        .HasForeignKey("SysLog.Domine.Model.Protocol", "LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("SysLog.Domine.Model.Signature", b =>
                {
                    b.HasOne("SysLog.Domine.Model.LogType", "LogType")
                        .WithOne("Signature")
                        .HasForeignKey("SysLog.Domine.Model.Signature", "LogTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogType");
                });

            modelBuilder.Entity("SysLog.Domine.Model.Log", b =>
                {
                    b.Navigation("Acction")
                        .IsRequired();

                    b.Navigation("Interface")
                        .IsRequired();

                    b.Navigation("LogType")
                        .IsRequired();

                    b.Navigation("Protocol")
                        .IsRequired();
                });

            modelBuilder.Entity("SysLog.Domine.Model.LogType", b =>
                {
                    b.Navigation("Signature")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
